services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    volumes:
      - ./n8n_data:/home/node/.n8n
      # Colleghiamo la cartella dei nodi compilati
      - ./custom_nodes/dist:/home/node/.n8n/custom/n8n-nodes-robot-controller
      # Colleghiamo la cartella dei workflow condivisi
      - ./workflows:/home/node/workflows
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        mkdir -p /home/node/workflows
        n8n import:workflow --separate --input=/home/node/workflows || true
        exec /docker-entrypoint.sh
